/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Session;

import Dashboard.Statistics1;
import Lecture_Location.Add_CRooms;
import Lecture_Location.Add_SRooms;
import Lecture_Location.Display_SRooms;
import Lecture_Location.lectureLocationNoAvii;
import Lecturer.Add_Lecturer;
import Lecturer.Manage_Lecturer;
import Location.AddLocations;
import Location.Manage_Locations;
import Student_Group.addStd;
import Student_Group.manageStd;
import Subjects.Add_Subject;
import Subjects.Manage_Subjects;
import Tags.addtag;
import Tags.managetag;
import Time_Allocations.addSession;
import WorkingDH.manageworkingday;
import WorkingDH.workingday;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.logging.Logger;
import java.util.logging.Level;

/**
 *
 * @author Amasha
 */
public class Add_Session extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Add_Session
     */
    public Add_Session() {
        initComponents();
        getLecturerName();
        getSubjectName();
        getSubjectCode();
        getGroupID();
        getTagName();
    }

    public void getLecturerName() {
        try {
            con = DB.DBConnect.getConnection();

            Statement stmt = con.createStatement();
            String query = "select lecturerName from lecturer";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                lecturerName.addItem(rs.getString("lecturerName"));
            }
        } catch(Exception e ) {
            System.out.println(e);
        }
    }
    
    public void getSubjectName() {
        try {
            con = DB.DBConnect.getConnection();
            
            Statement stmt = con.createStatement();
            String query = "select subjectName from subjects";
            
            ResultSet rs = stmt.executeQuery(query);
            
            while (rs.next()) {
                subjectName.addItem(rs.getString("subjectName"));
            }
        } catch(Exception e ) {
            System.out.println(e);
        }
    }  
    
    public void getSubjectCode() {
        try {
            con = DB.DBConnect.getConnection();

            Statement stmt = con.createStatement();
            String query = "select subjectCode from subjects";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                subjectCode.addItem(rs.getString("subjectCode"));
            }
        } catch(Exception e ) {
            System.out.println(e);
        }
    }

    public void getGroupID() {
        try {
            con = DB.DBConnect.getConnection();

            Statement stmt = con.createStatement();
            String query = "select grup_id from student_group";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                groupID.addItem(rs.getString("grup_id"));
            }
        } catch(Exception e ) {
            System.out.println(e);
        }
    }  
    
    public void getTagName() {
        try {
            con = DB.DBConnect.getConnection();

            Statement stmt = con.createStatement();
            String query = "select tag_name from tags";

            ResultSet rs = stmt.executeQuery(query);

            while (rs.next()) {
                tags.addItem(rs.getString("tag_name"));
            }
        } catch(Exception e ) {
            System.out.println(e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lableDashboard = new javax.swing.JLabel();
        labelLecturer = new javax.swing.JLabel();
        labelAddLecturer = new javax.swing.JLabel();
        labelManageLecturer = new javax.swing.JLabel();
        labelSubject = new javax.swing.JLabel();
        labelAddSubject = new javax.swing.JLabel();
        labelManageSubjects = new javax.swing.JLabel();
        labelStudentGroup = new javax.swing.JLabel();
        labelAddSG = new javax.swing.JLabel();
        labelManageSG = new javax.swing.JLabel();
        labelTags = new javax.swing.JLabel();
        labelAddTag = new javax.swing.JLabel();
        labelManageTag = new javax.swing.JLabel();
        labelWorkingDaysHours = new javax.swing.JLabel();
        labelAddWDH = new javax.swing.JLabel();
        labelManageWDH = new javax.swing.JLabel();
        labelLocations = new javax.swing.JLabel();
        labelAddLocation = new javax.swing.JLabel();
        labelManageLocation = new javax.swing.JLabel();
        labelSession = new javax.swing.JLabel();
        labelAddSession = new javax.swing.JLabel();
        labelManageSession = new javax.swing.JLabel();
        labelLectureLocation = new javax.swing.JLabel();
        labelManageLectureLocation = new javax.swing.JLabel();
        labelAddS = new javax.swing.JLabel();
        labelAddCS = new javax.swing.JLabel();
        labelAddNAR = new javax.swing.JLabel();
        labelTimeAloocation = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelGroupID = new javax.swing.JLabel();
        labelNoOfStudents = new javax.swing.JLabel();
        noOfStudents = new javax.swing.JTextField();
        labelDuration = new javax.swing.JLabel();
        labelTag = new javax.swing.JLabel();
        labelSelectLecturer = new javax.swing.JLabel();
        labelSelectedLecturers = new javax.swing.JLabel();
        lecturerName = new javax.swing.JComboBox<>();
        lecturerNameSelected = new javax.swing.JComboBox<>();
        llabelSubjectName = new javax.swing.JLabel();
        subjectName = new javax.swing.JComboBox<>();
        groupID = new javax.swing.JComboBox<>();
        duration = new javax.swing.JTextField();
        labelSubjectCode = new javax.swing.JLabel();
        subjectCode = new javax.swing.JComboBox<>();
        tags = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        Error_LN = new javax.swing.JLabel();
        Error_LN1 = new javax.swing.JLabel();
        Error_LN2 = new javax.swing.JLabel();
        Error_LN3 = new javax.swing.JLabel();
        Error_LN4 = new javax.swing.JLabel();
        Error_LN5 = new javax.swing.JLabel();
        Error_LN6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(36, 190, 135));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(149, 249, 174));

        lableDashboard.setBackground(new java.awt.Color(51, 153, 0));
        lableDashboard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lableDashboard.setText("Dashboard");
        lableDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableDashboardMouseClicked(evt);
            }
        });

        labelLecturer.setBackground(new java.awt.Color(51, 204, 0));
        labelLecturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLecturer.setText("Lecturer");

        labelAddLecturer.setText("Add a Lecturer");
        labelAddLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddLecturerMouseClicked(evt);
            }
        });

        labelManageLecturer.setText("Manage Lecturers");
        labelManageLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageLecturerMouseClicked(evt);
            }
        });

        labelSubject.setBackground(new java.awt.Color(51, 204, 0));
        labelSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSubject.setText("Subject");

        labelAddSubject.setText("Add a Subject");
        labelAddSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSubjectMouseClicked(evt);
            }
        });

        labelManageSubjects.setText("Manage Subjects");
        labelManageSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageSubjectsMouseClicked(evt);
            }
        });

        labelStudentGroup.setBackground(new java.awt.Color(51, 204, 0));
        labelStudentGroup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStudentGroup.setText("Student Groups");

        labelAddSG.setText("Add a Student Group");
        labelAddSG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSGMouseClicked(evt);
            }
        });

        labelManageSG.setText("Manage Student Groups");
        labelManageSG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageSGMouseClicked(evt);
            }
        });

        labelTags.setBackground(new java.awt.Color(51, 204, 0));
        labelTags.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTags.setText("Tags");

        labelAddTag.setText("Add a Tag");
        labelAddTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddTagMouseClicked(evt);
            }
        });

        labelManageTag.setText("Manage Tags");
        labelManageTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageTagMouseClicked(evt);
            }
        });

        labelWorkingDaysHours.setBackground(new java.awt.Color(51, 204, 0));
        labelWorkingDaysHours.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelWorkingDaysHours.setText("Working Days & Hours");

        labelAddWDH.setText("Add Working Days & Hours");
        labelAddWDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddWDHMouseClicked(evt);
            }
        });

        labelManageWDH.setText("Manage Working Days & Hours");
        labelManageWDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageWDHMouseClicked(evt);
            }
        });

        labelLocations.setBackground(new java.awt.Color(51, 204, 0));
        labelLocations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLocations.setText("Locations");

        labelAddLocation.setText("Add a Locations");
        labelAddLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddLocationMouseClicked(evt);
            }
        });

        labelManageLocation.setText("Manage Locations");
        labelManageLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageLocationMouseClicked(evt);
            }
        });

        labelSession.setBackground(new java.awt.Color(51, 204, 0));
        labelSession.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSession.setText("Sessions");

        labelAddSession.setText("Add a Session");
        labelAddSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSessionMouseClicked(evt);
            }
        });

        labelManageSession.setText("Manage Sessions");
        labelManageSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageSessionMouseClicked(evt);
            }
        });

        labelLectureLocation.setBackground(new java.awt.Color(51, 204, 0));
        labelLectureLocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLectureLocation.setText("Lecture Locations");

        labelManageLectureLocation.setText("Manage Lecture Locations");
        labelManageLectureLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageLectureLocationMouseClicked(evt);
            }
        });

        labelAddS.setText("Add a Sessions");
        labelAddS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSMouseClicked(evt);
            }
        });

        labelAddCS.setText("Add a Consecutive Sessions");
        labelAddCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddCSMouseClicked(evt);
            }
        });

        labelAddNAR.setText("Add Not Available Room");
        labelAddNAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddNARMouseClicked(evt);
            }
        });

        labelTimeAloocation.setBackground(new java.awt.Color(51, 204, 0));
        labelTimeAloocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTimeAloocation.setText("Time Allocation");
        labelTimeAloocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTimeAloocationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddWDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageWDH, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(labelAddLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageLectureLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddNAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lableDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLecturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelStudentGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTags, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelWorkingDaysHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLocations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLectureLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTimeAloocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lableDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageSubjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStudentGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWorkingDaysHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddWDH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageWDH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLocations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLectureLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageLectureLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddCS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddNAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTimeAloocation)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add A Session");

        labelGroupID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelGroupID.setText("Select Group ID");

        labelNoOfStudents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNoOfStudents.setText("Number of Students");

        noOfStudents.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelDuration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDuration.setText("Duration(Hours)");

        labelTag.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTag.setText("Select Tag(s)");

        labelSelectLecturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSelectLecturer.setText("Select Lecturer");

        labelSelectedLecturers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSelectedLecturers.setText("Select Lecturer(s)");

        lecturerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lecturerName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));
        lecturerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturerNameActionPerformed(evt);
            }
        });

        lecturerNameSelected.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        llabelSubjectName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        llabelSubjectName.setText("Select Subject ");

        subjectName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subjectName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));

        groupID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        groupID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));

        duration.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        labelSubjectCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSubjectCode.setText("Select Subject Code");

        subjectCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        subjectCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));

        tags.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tags.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT" }));

        SaveButton.setBackground(new java.awt.Color(204, 255, 0));
        SaveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setToolTipText("Save Data");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        clearButton.setBackground(new java.awt.Color(255, 204, 0));
        clearButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearButton.setText("Clear All");
        clearButton.setToolTipText("Clear Data");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        Error_LN.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN1.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN2.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN3.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN4.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN5.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN6.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lecturerNameSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelSelectedLecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(694, 694, 694))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(Error_LN2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(174, 174, 174)
                                            .addComponent(Error_LN3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(groupID, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(labelSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(subjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelNoOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(Error_LN4, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(174, 174, 174)
                                            .addComponent(Error_LN5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(noOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(labelTag, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tags, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(labelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(Error_LN6, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(128, 128, 128)
                                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(48, 48, 48)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelSelectLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(Error_LN1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(174, 174, 174)
                                        .addComponent(Error_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(lecturerName, 0, 258, Short.MAX_VALUE)
                                        .addGap(37, 37, 37)
                                        .addComponent(llabelSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(subjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelDuration, labelGroupID, labelNoOfStudents, labelSelectLecturer, labelSelectedLecturers, labelSubjectCode, labelTag, llabelSubjectName});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {duration, groupID, lecturerName, noOfStudents, subjectCode, subjectName, tags});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {SaveButton, clearButton});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Error_LN, Error_LN1});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelectLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(llabelSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error_LN1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSelectedLecturers, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lecturerNameSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGroupID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(groupID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error_LN2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error_LN3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTag, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tags, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Error_LN4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Error_LN5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duration, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Error_LN6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelDuration, labelGroupID, labelNoOfStudents, labelSelectLecturer, labelSelectedLecturers, labelSubjectCode, labelTag, llabelSubjectName});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {duration, groupID, lecturerName, lecturerNameSelected, noOfStudents, subjectCode, subjectName, tags});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Error_LN, Error_LN1});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelManageLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageLecturerMouseClicked
        // TODO add your handling code here:
        Manage_Lecturer ml = new Manage_Lecturer();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageLecturerMouseClicked

    private void labelAddSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSubjectMouseClicked
        // TODO add your handling code here:
        Add_Subject as = new Add_Subject();
        as.setVisible(true);
        as.pack();
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddSubjectMouseClicked

    private void labelManageSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageSubjectsMouseClicked
        // TODO add your handling code here:
        Manage_Subjects ms = new Manage_Subjects();
        ms.setVisible(true);
        ms.pack();
        ms.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageSubjectsMouseClicked

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if((lecturerName.getSelectedItem() == "SELECT")&& (subjectName.getSelectedItem() == "SELECT") && (subjectCode.getSelectedItem() == "SELECT") && (groupID.getSelectedItem() == "SELECT") && (tags.getSelectedItem() == "SELECT") && (noOfStudents.getText().trim().isEmpty()) && (duration.getText().trim().isEmpty())) {
            Error_LN1.setText("Lecturer Name is not selected!");
            Error_LN.setText("Subject Name is not selected!");
            Error_LN3.setText("Subject Code is not selected!");
            Error_LN2.setText("Group ID is not selected!");
            Error_LN5.setText("Tag Name is not selected!");
            Error_LN4.setText("Number of Students is empty!");
            Error_LN6.setText("Duration is empty!");
        }else if (lecturerName.getSelectedItem() == "SELECT") {
            Error_LN1.setText("Lecturer Name is not selected!");
        }else if (subjectName.getSelectedItem() == "SELECT") {
            Error_LN.setText("Subject Name is not selected!");
        }else if (subjectCode.getSelectedItem() == "SELECT") {
            Error_LN3.setText("Subject Code is not selected!");
        }else if (groupID.getSelectedItem() == "SELECT") {
            Error_LN2.setText("Group ID is not selected!");
        }else if (tags.getSelectedItem() == "SELECT") {
            Error_LN5.setText("Tag Name is not selected!");
        }else if (noOfStudents.getText().trim().isEmpty()) {
            Error_LN4.setText("Number of Students is empty!");
        }else if (duration.getText().trim().isEmpty()) {
            Error_LN6.setText("Duration is empty!");
        }else {
            try{
                int count = lecturerNameSelected.getItemCount();

                con = DB.DBConnect.getConnection(); 
                pst = con.prepareStatement("insert into sessions(lecturerName1,lecturerName2,subjectName,subjectCode,groupID,tag,noOfStudents,duration)value(?,?,?,?,?,?,?,?)");
                
                if (count == 1) {
                    lecturerNameSelected.setSelectedIndex(0);
                    pst.setString(1, (String) lecturerNameSelected.getSelectedItem());
                    String s = "";
                    pst.setString(2, s);
                    pst.setString(3, (String) subjectName.getSelectedItem());
                    pst.setString(4, (String) subjectCode.getSelectedItem());
                    pst.setString(5, (String) groupID.getSelectedItem());
                    pst.setString(6, (String) tags.getSelectedItem());
                    pst.setString(7, noOfStudents.getText());
                    pst.setString(8, duration.getText());
                }

                if (count == 2) {
                    lecturerNameSelected.setSelectedIndex(0);
                    pst.setString(1, (String) lecturerNameSelected.getSelectedItem());
                    lecturerNameSelected.setSelectedIndex(1);
                    pst.setString(2, (String) lecturerNameSelected.getSelectedItem());
                    pst.setString(3, (String) subjectName.getSelectedItem());
                    pst.setString(4, (String) subjectCode.getSelectedItem());
                    pst.setString(5, (String) groupID.getSelectedItem());
                    pst.setString(6, (String) tags.getSelectedItem());
                    pst.setString(7, noOfStudents.getText());
                    pst.setString(8, duration.getText());
                }
         
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Added Successfully");

                lecturerName.setSelectedIndex(0);
                lecturerNameSelected.removeAllItems();
                subjectName.setSelectedIndex(0);
                subjectCode.setSelectedIndex(0);
                groupID.setSelectedIndex(0);
                noOfStudents.setText("");
                tags.setSelectedIndex(0);
                duration.setText("");
                
                //Clear Error fields
                Error_LN1.setText("");
                Error_LN.setText("");
                Error_LN3.setText("");
                Error_LN2.setText("");
                Error_LN5.setText("");
                Error_LN4.setText("");
                Error_LN6.setText("");
                
            } catch (SQLException e) {
                Logger.getLogger(Add_Session.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        lecturerName.setSelectedIndex(0);
        lecturerNameSelected.removeAllItems();
        subjectName.setSelectedIndex(0);
        subjectCode.setSelectedIndex(0);
        groupID.setSelectedIndex(0);
        noOfStudents.setText("");
        tags.setSelectedIndex(0);
        duration.setText("");
        
        Error_LN1.setText("");
        Error_LN.setText("");
        Error_LN3.setText("");
        Error_LN2.setText("");
        Error_LN5.setText("");
        Error_LN4.setText("");
        Error_LN6.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void labelAddLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddLecturerMouseClicked
        Add_Lecturer al = new Add_Lecturer();
        al.setVisible(true);
        al.pack();
        al.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddLecturerMouseClicked

    private void labelManageSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageSessionMouseClicked
        Manage_Session ms = new Manage_Session();
        ms.setVisible(true);
        ms.pack();
        ms.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageSessionMouseClicked

    private void lecturerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturerNameActionPerformed
        lecturerNameSelected.addItem((String) lecturerName.getSelectedItem());

        int size = lecturerNameSelected.getItemCount();
        
        if (size > 2) {
            lecturerNameSelected.removeAllItems(); 
            JOptionPane.showMessageDialog(this, "Only 2 lectures can be selected.\nSelected names will be removed.\nPlease select again.");
        }
    }//GEN-LAST:event_lecturerNameActionPerformed

    private void lableDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableDashboardMouseClicked
        Statistics1 ml = new Statistics1();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lableDashboardMouseClicked

    private void labelAddSGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSGMouseClicked
        addStd ml = new addStd();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_labelAddSGMouseClicked

    private void labelManageSGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageSGMouseClicked
        manageStd ml = new manageStd();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  
    }//GEN-LAST:event_labelManageSGMouseClicked

    private void labelAddTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddTagMouseClicked
        addtag ml = new addtag();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddTagMouseClicked

    private void labelManageTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageTagMouseClicked
        managetag ml = new managetag();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageTagMouseClicked

    private void labelAddWDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddWDHMouseClicked
        workingday ml = new workingday();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddWDHMouseClicked

    private void labelManageWDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageWDHMouseClicked
        manageworkingday ml = new manageworkingday();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageWDHMouseClicked

    private void labelAddLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddLocationMouseClicked
        AddLocations ml = new AddLocations();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddLocationMouseClicked

    private void labelManageLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageLocationMouseClicked
        Manage_Locations ml = new Manage_Locations();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageLocationMouseClicked

    private void labelAddSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSessionMouseClicked
        Add_Session ml = new Add_Session();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddSessionMouseClicked

    private void labelManageLectureLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageLectureLocationMouseClicked
        Display_SRooms ml = new Display_SRooms();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageLectureLocationMouseClicked

    private void labelAddSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSMouseClicked
        Add_SRooms ml = new Add_SRooms();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddSMouseClicked

    private void labelAddCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddCSMouseClicked
        Add_CRooms ml = new Add_CRooms();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddCSMouseClicked

    private void labelAddNARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddNARMouseClicked
        lectureLocationNoAvii ml = new lectureLocationNoAvii();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddNARMouseClicked

    private void labelTimeAloocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeAloocationMouseClicked
        addSession ml = new addSession();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelTimeAloocationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Session().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Error_LN;
    private javax.swing.JLabel Error_LN1;
    private javax.swing.JLabel Error_LN2;
    private javax.swing.JLabel Error_LN3;
    private javax.swing.JLabel Error_LN4;
    private javax.swing.JLabel Error_LN5;
    private javax.swing.JLabel Error_LN6;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton clearButton;
    public javax.swing.JTextField duration;
    public javax.swing.JComboBox<String> groupID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAddCS;
    private javax.swing.JLabel labelAddLecturer;
    private javax.swing.JLabel labelAddLocation;
    private javax.swing.JLabel labelAddNAR;
    private javax.swing.JLabel labelAddS;
    private javax.swing.JLabel labelAddSG;
    private javax.swing.JLabel labelAddSession;
    private javax.swing.JLabel labelAddSubject;
    private javax.swing.JLabel labelAddTag;
    private javax.swing.JLabel labelAddWDH;
    private javax.swing.JLabel labelDuration;
    private javax.swing.JLabel labelGroupID;
    private javax.swing.JLabel labelLectureLocation;
    private javax.swing.JLabel labelLecturer;
    private javax.swing.JLabel labelLocations;
    private javax.swing.JLabel labelManageLectureLocation;
    private javax.swing.JLabel labelManageLecturer;
    private javax.swing.JLabel labelManageLocation;
    private javax.swing.JLabel labelManageSG;
    private javax.swing.JLabel labelManageSession;
    private javax.swing.JLabel labelManageSubjects;
    private javax.swing.JLabel labelManageTag;
    private javax.swing.JLabel labelManageWDH;
    private javax.swing.JLabel labelNoOfStudents;
    private javax.swing.JLabel labelSelectLecturer;
    private javax.swing.JLabel labelSelectedLecturers;
    private javax.swing.JLabel labelSession;
    private javax.swing.JLabel labelStudentGroup;
    private javax.swing.JLabel labelSubject;
    private javax.swing.JLabel labelSubjectCode;
    private javax.swing.JLabel labelTag;
    private javax.swing.JLabel labelTags;
    private javax.swing.JLabel labelTimeAloocation;
    private javax.swing.JLabel labelWorkingDaysHours;
    private javax.swing.JLabel lableDashboard;
    public javax.swing.JComboBox<String> lecturerName;
    public javax.swing.JComboBox<String> lecturerNameSelected;
    private javax.swing.JLabel llabelSubjectName;
    public javax.swing.JTextField noOfStudents;
    public javax.swing.JComboBox<String> subjectCode;
    public javax.swing.JComboBox<String> subjectName;
    public javax.swing.JComboBox<String> tags;
    // End of variables declaration//GEN-END:variables
}
