/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lecturer;

import Dashboard.Statistics1;
import Lecture_Location.Add_CRooms;
import Lecture_Location.Add_SRooms;
import Lecture_Location.Display_SRooms;
import Lecture_Location.lectureLocationNoAvii;
import Location.AddLocations;
import Location.Manage_Locations;
import Session.Add_Session;
import Session.Manage_Session;
import Student_Group.addStd;
import Student_Group.manageStd;
import Subjects.Add_Subject;
import Subjects.Manage_Subjects;
import Tags.addtag;
import Tags.managetag;
import Time_Allocations.addSession;
import WorkingDH.manageworkingday;
import WorkingDH.workingday;
import java.util.logging.Logger;
import java.util.logging.Level;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import javax.swing.JFrame;


/**
 *
 * @author Amasha
 */
public class Add_Lecturer extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Add_Lecturer
     */
    public Add_Lecturer() {
        initComponents();
        Ranks.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lableDashboard = new javax.swing.JLabel();
        labelLecturer = new javax.swing.JLabel();
        labelAddLecturer = new javax.swing.JLabel();
        labelManageLecturer = new javax.swing.JLabel();
        labelSubject = new javax.swing.JLabel();
        labelAddSubject = new javax.swing.JLabel();
        labelManageSubjects = new javax.swing.JLabel();
        labelStudentGroup = new javax.swing.JLabel();
        labelAddSG = new javax.swing.JLabel();
        labelManageSG = new javax.swing.JLabel();
        labelTags = new javax.swing.JLabel();
        labelAddTag = new javax.swing.JLabel();
        labelManageTag = new javax.swing.JLabel();
        labelWorkingDaysHours = new javax.swing.JLabel();
        labelAddWDH = new javax.swing.JLabel();
        labelManageWDH = new javax.swing.JLabel();
        labelLocations = new javax.swing.JLabel();
        labelAddLocation = new javax.swing.JLabel();
        labelManageLocation = new javax.swing.JLabel();
        labelSession = new javax.swing.JLabel();
        labelAddSession = new javax.swing.JLabel();
        labelManageSession = new javax.swing.JLabel();
        labelLectureLocation = new javax.swing.JLabel();
        labelManageLectureLocation = new javax.swing.JLabel();
        labelAddS = new javax.swing.JLabel();
        labelAddCS = new javax.swing.JLabel();
        labelAddNAR = new javax.swing.JLabel();
        labelTimeAloocation = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lableLectuereName = new javax.swing.JLabel();
        labelEmployeeID = new javax.swing.JLabel();
        labelFaculty = new javax.swing.JLabel();
        labelDepartment = new javax.swing.JLabel();
        labelCenter = new javax.swing.JLabel();
        labelBuilding = new javax.swing.JLabel();
        labelLevel = new javax.swing.JLabel();
        labelRank = new javax.swing.JLabel();
        Lecturer_Name = new javax.swing.JTextField();
        Employee_ID = new javax.swing.JTextField();
        Faculty = new javax.swing.JComboBox<>();
        level = new javax.swing.JComboBox<>();
        Department = new javax.swing.JComboBox<>();
        Center = new javax.swing.JComboBox<>();
        Building = new javax.swing.JComboBox<>();
        Ranks = new javax.swing.JTextField();
        ClearButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        GenerateRankButton = new javax.swing.JButton();
        Error_Dept = new javax.swing.JLabel();
        Error_Rank = new javax.swing.JLabel();
        Error_EID = new javax.swing.JLabel();
        Error_F = new javax.swing.JLabel();
        Error_LN = new javax.swing.JLabel();
        Error_Level = new javax.swing.JLabel();
        Error_Center = new javax.swing.JLabel();
        Error_Building = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(149, 249, 174));

        lableDashboard.setBackground(new java.awt.Color(51, 153, 0));
        lableDashboard.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lableDashboard.setText("Dashboard");
        lableDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lableDashboardMouseClicked(evt);
            }
        });

        labelLecturer.setBackground(new java.awt.Color(51, 204, 0));
        labelLecturer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLecturer.setText("Lecturer");

        labelAddLecturer.setText("Add a Lecturer");
        labelAddLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddLecturerMouseClicked(evt);
            }
        });

        labelManageLecturer.setText("Manage Lecturers");
        labelManageLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageLecturerMouseClicked(evt);
            }
        });

        labelSubject.setBackground(new java.awt.Color(51, 204, 0));
        labelSubject.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSubject.setText("Subject");

        labelAddSubject.setText("Add a Subject");
        labelAddSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSubjectMouseClicked(evt);
            }
        });

        labelManageSubjects.setText("Manage Subjects");
        labelManageSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageSubjectsMouseClicked(evt);
            }
        });

        labelStudentGroup.setBackground(new java.awt.Color(51, 204, 0));
        labelStudentGroup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelStudentGroup.setText("Student Groups");

        labelAddSG.setText("Add a Student Group");
        labelAddSG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSGMouseClicked(evt);
            }
        });

        labelManageSG.setText("Manage Student Groups");
        labelManageSG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageSGMouseClicked(evt);
            }
        });

        labelTags.setBackground(new java.awt.Color(51, 204, 0));
        labelTags.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTags.setText("Tags");

        labelAddTag.setText("Add a Tag");
        labelAddTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddTagMouseClicked(evt);
            }
        });

        labelManageTag.setText("Manage Tags");
        labelManageTag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageTagMouseClicked(evt);
            }
        });

        labelWorkingDaysHours.setBackground(new java.awt.Color(51, 204, 0));
        labelWorkingDaysHours.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelWorkingDaysHours.setText("Working Days & Hours");

        labelAddWDH.setText("Add Working Days & Hours");
        labelAddWDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddWDHMouseClicked(evt);
            }
        });

        labelManageWDH.setText("Manage Working Days & Hours");
        labelManageWDH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageWDHMouseClicked(evt);
            }
        });

        labelLocations.setBackground(new java.awt.Color(51, 204, 0));
        labelLocations.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLocations.setText("Locations");

        labelAddLocation.setText("Add a Locations");
        labelAddLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddLocationMouseClicked(evt);
            }
        });

        labelManageLocation.setText("Manage Locations");
        labelManageLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageLocationMouseClicked(evt);
            }
        });

        labelSession.setBackground(new java.awt.Color(51, 204, 0));
        labelSession.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelSession.setText("Sessions");

        labelAddSession.setText("Add a Session");
        labelAddSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSessionMouseClicked(evt);
            }
        });

        labelManageSession.setText("Manage Sessions");
        labelManageSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageSessionMouseClicked(evt);
            }
        });

        labelLectureLocation.setBackground(new java.awt.Color(51, 204, 0));
        labelLectureLocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLectureLocation.setText("Lecture Locations");

        labelManageLectureLocation.setText("Manage Lecture Locations");
        labelManageLectureLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelManageLectureLocationMouseClicked(evt);
            }
        });

        labelAddS.setText("Add a Sessions");
        labelAddS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddSMouseClicked(evt);
            }
        });

        labelAddCS.setText("Add a Consecutive Sessions");
        labelAddCS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddCSMouseClicked(evt);
            }
        });

        labelAddNAR.setText("Add Not Available Room");
        labelAddNAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAddNARMouseClicked(evt);
            }
        });

        labelTimeAloocation.setBackground(new java.awt.Color(51, 204, 0));
        labelTimeAloocation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelTimeAloocation.setText("Time Allocation");
        labelTimeAloocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelTimeAloocationMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageLecturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageSG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddWDH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageWDH, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(labelAddLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageSession, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelManageLectureLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddCS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelAddNAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lableDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLecturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSubject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelStudentGroup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTags, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelWorkingDaysHours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLocations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelSession, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelLectureLocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labelTimeAloocation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lableDashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageLecturer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddSubject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageSubjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStudentGroup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageSG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageTag)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelWorkingDaysHours)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddWDH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageWDH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLocations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLectureLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelManageLectureLocation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddCS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddNAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTimeAloocation)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Lecturer");

        lableLectuereName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lableLectuereName.setText("Lecturer Name");

        labelEmployeeID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelEmployeeID.setText("Employee ID");

        labelFaculty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelFaculty.setText("Faculty");

        labelDepartment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelDepartment.setText("Department");

        labelCenter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCenter.setText("Center");

        labelBuilding.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelBuilding.setText("Building");

        labelLevel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLevel.setText("Level");

        labelRank.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelRank.setText("Rank");

        Faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Faculty of Computing", "Faculty of Engineering" }));

        level.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "1", "2", "3", "4", "5", "6" }));

        Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Software Engineering", "Data Science", "Information Technology", "Cyber Security" }));

        Center.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Malabe", "Metropoliton", "Matara", "Kurunagala", "Jaffna" }));

        Building.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Main Building", "New Building" }));

        ClearButton.setBackground(new java.awt.Color(255, 64, 0));
        ClearButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear All");
        ClearButton.setToolTipText("Clear Data");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        SaveButton.setBackground(new java.awt.Color(0, 230, 0));
        SaveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.setToolTipText("Save Data");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        GenerateRankButton.setBackground(new java.awt.Color(255, 204, 0));
        GenerateRankButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        GenerateRankButton.setForeground(new java.awt.Color(255, 255, 255));
        GenerateRankButton.setText("Generate Rank");
        GenerateRankButton.setToolTipText("Generate Rank Automatically");
        GenerateRankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateRankButtonActionPerformed(evt);
            }
        });

        Error_Dept.setForeground(new java.awt.Color(255, 0, 51));

        Error_Rank.setForeground(new java.awt.Color(255, 0, 51));

        Error_EID.setForeground(new java.awt.Color(255, 0, 51));

        Error_F.setForeground(new java.awt.Color(255, 0, 51));

        Error_LN.setForeground(new java.awt.Color(255, 0, 51));

        Error_Level.setForeground(new java.awt.Color(255, 0, 51));

        Error_Center.setForeground(new java.awt.Color(255, 0, 51));

        Error_Building.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lableLectuereName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Error_EID, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lecturer_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(Employee_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(Error_LN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Error_F, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Department, 0, 171, Short.MAX_VALUE)
                                    .addComponent(Error_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Faculty, 0, 171, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCenter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBuilding, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenerateRankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Center, 0, 213, Short.MAX_VALUE)
                            .addComponent(level, 0, 213, Short.MAX_VALUE)
                            .addComponent(Error_Rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Error_Level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ranks, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                            .addComponent(Error_Building, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Building, 0, 213, Short.MAX_VALUE)
                            .addComponent(Error_Center, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelBuilding, labelCenter, labelDepartment, labelEmployeeID, labelFaculty, labelLevel, labelRank, lableLectuereName});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Building, Center, Department, Employee_ID, Faculty, Lecturer_Name, Ranks, level});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ClearButton, GenerateRankButton, SaveButton});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lableLectuereName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Center, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addComponent(Error_Center, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Building, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Error_Building, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Error_Level, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Ranks, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Error_Rank, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Lecturer_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Error_LN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Employee_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Error_EID, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(Error_F, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Error_Dept, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(labelBuilding, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(labelDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(labelRank, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateRankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelBuilding, labelCenter, labelDepartment, labelEmployeeID, labelFaculty, labelLevel, labelRank, lableLectuereName});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Building, Center, Department, Employee_ID, Faculty, Lecturer_Name, Ranks, level});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Error_Dept, Error_EID, Error_F, Error_LN});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ClearButton, GenerateRankButton, SaveButton});

        jPanel2.setBackground(new java.awt.Color(36, 190, 135));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelManageLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageLecturerMouseClicked
        // TODO add your handling code here:
        Manage_Lecturer ml = new Manage_Lecturer();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageLecturerMouseClicked

    private void labelAddSubjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSubjectMouseClicked
        // TODO add your handling code here:
        Add_Subject as = new Add_Subject();
        as.setVisible(true);
        as.pack();
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddSubjectMouseClicked

    private void labelManageSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageSubjectsMouseClicked
        // TODO add your handling code here:
        Manage_Subjects ms = new Manage_Subjects();
        ms.setVisible(true);
        ms.pack();
        ms.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageSubjectsMouseClicked

    private void GenerateRankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateRankButtonActionPerformed
        // TODO add your handling code here:
        String a = (String) level.getSelectedItem();
        String b = Employee_ID.getText();

        Ranks.setText(a+"."+b);
    }//GEN-LAST:event_GenerateRankButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        if (Lecturer_Name.getText().trim().isEmpty() && Employee_ID.getText().trim().isEmpty() && Faculty.getSelectedItem() == "SELECT" && Department.getSelectedItem() == "SELECT" && (Center.getSelectedItem() == "SELECT") && (Building.getSelectedItem() == "SELECT") && (level.getSelectedItem() == "SELECT") && (Ranks.getText().trim().isEmpty())) {
            Error_LN.setText("Lecturer Name is empty!");
            Error_EID.setText("Employee ID is empty!");
            Error_F.setText("Faculty is not selected!");
            Error_Dept.setText("Department is not selected!");
            Error_Center.setText("Center is not selected!");
            Error_Building.setText("Building is not selected!");
            Error_Rank.setText("Rank is not generated!");
            Error_Level.setText("Level is not selected!");
        } else if (Employee_ID.getText().trim().isEmpty()){
            Error_EID.setText("Employee ID is empty!");
        } else if (Lecturer_Name.getText().trim().isEmpty()) {
            Error_LN.setText("Lecturer Name is empty!");
        } else if (Faculty.getSelectedItem() == "SELECT") {
            Error_F.setText("Faculty is not selected!");
        } else if (Department.getSelectedItem() == "SELECT") {
            Error_Dept.setText("Department is not selected!");
        } else if (Center.getSelectedItem() == "SELECT") {
            Error_Center.setText("Center is not selected!");
        } else if (Building.getSelectedItem() == "SELECT") {
            Error_Building.setText("Building is not selected!");
        } else if (level.getSelectedItem() == "SELECT") {
            Error_Level.setText("Level is not selected!");
        } else if (Ranks.getText().trim().isEmpty()) {
            Error_Rank.setText("Rank is not generated!");
        }
        else
        {
            try{
                con = DB.DBConnect.getConnection();
                pst = con.prepareStatement("insert into lecturer(lecturerName,employeeID,faculty,department,center,building,level,ranks)value(?,?,?,?,?,?,?,?)");

                pst.setString(1, Lecturer_Name.getText());
                pst.setString(2, Employee_ID.getText());
                pst.setString(3, (String) Faculty.getSelectedItem());
                pst.setString(4, (String) Department.getSelectedItem());
                pst.setString(5, (String) Center.getSelectedItem());
                pst.setString(6, (String) Building.getSelectedItem());
                pst.setString(7, (String) level.getSelectedItem());
                pst.setString(8, Ranks.getText());

                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Added Successfully");
                
                Lecturer_Name.setText("");
                Employee_ID.setText("");
                Faculty.setSelectedIndex(0);
                Department.setSelectedIndex(0);
                Center.setSelectedIndex(0);
                Building.setSelectedIndex(0);
                level.setSelectedIndex(0);
                Ranks.setText("");
                
                Error_LN.setText("");
                Error_EID.setText("");
                Error_F.setText("");
                Error_Dept.setText("");
                Error_Center.setText("");
                Error_Building.setText("");
                Error_Rank.setText("");
                Error_Level.setText("");
            } catch (SQLException e) {
                Logger.getLogger(Add_Lecturer.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        Lecturer_Name.setText("");
        Employee_ID.setText("");
        Faculty.setSelectedIndex(0);
        Department.setSelectedIndex(0);
        Center.setSelectedIndex(0);
        Building.setSelectedIndex(0);
        level.setSelectedIndex(0);
        Ranks.setText("");
        
        Error_LN.setText("");
        Error_EID.setText("");
        Error_F.setText("");
        Error_Dept.setText("");
        Error_Center.setText("");
        Error_Building.setText("");
        Error_Rank.setText("");
        Error_Level.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void labelAddSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSessionMouseClicked
        Add_Session as = new Add_Session();
        as.setVisible(true);
        as.pack();
        as.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddSessionMouseClicked

    private void labelManageSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageSessionMouseClicked
        Manage_Session ms = new Manage_Session();
        ms.setVisible(true);
        ms.pack();
        ms.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageSessionMouseClicked

    private void labelAddLecturerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddLecturerMouseClicked
        Add_Lecturer ml = new Add_Lecturer();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddLecturerMouseClicked

    private void lableDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lableDashboardMouseClicked
        Statistics1 ml = new Statistics1();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lableDashboardMouseClicked

    private void labelAddSGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSGMouseClicked
        addStd ml = new addStd();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }//GEN-LAST:event_labelAddSGMouseClicked

    private void labelManageSGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageSGMouseClicked
        manageStd ml = new manageStd();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();  
    }//GEN-LAST:event_labelManageSGMouseClicked

    private void labelAddTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddTagMouseClicked
        addtag ml = new addtag();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddTagMouseClicked

    private void labelManageTagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageTagMouseClicked
        managetag ml = new managetag();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageTagMouseClicked

    private void labelAddWDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddWDHMouseClicked
        workingday ml = new workingday();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddWDHMouseClicked

    private void labelManageWDHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageWDHMouseClicked
        manageworkingday ml = new manageworkingday();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageWDHMouseClicked

    private void labelAddLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddLocationMouseClicked
        AddLocations ml = new AddLocations();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddLocationMouseClicked

    private void labelManageLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageLocationMouseClicked
        Manage_Locations ml = new Manage_Locations();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageLocationMouseClicked

    private void labelManageLectureLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelManageLectureLocationMouseClicked
        Display_SRooms ml = new Display_SRooms();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelManageLectureLocationMouseClicked

    private void labelAddSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddSMouseClicked
        Add_SRooms ml = new Add_SRooms();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddSMouseClicked

    private void labelAddCSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddCSMouseClicked
        Add_CRooms ml = new Add_CRooms();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddCSMouseClicked

    private void labelAddNARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAddNARMouseClicked
        lectureLocationNoAvii ml = new lectureLocationNoAvii();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelAddNARMouseClicked

    private void labelTimeAloocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelTimeAloocationMouseClicked
        addSession ml = new addSession();
        ml.setVisible(true);
        ml.pack();
        ml.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_labelTimeAloocationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Building;
    private javax.swing.JComboBox<String> Center;
    private javax.swing.JButton ClearButton;
    private javax.swing.JComboBox<String> Department;
    private javax.swing.JTextField Employee_ID;
    private javax.swing.JLabel Error_Building;
    private javax.swing.JLabel Error_Center;
    private javax.swing.JLabel Error_Dept;
    private javax.swing.JLabel Error_EID;
    private javax.swing.JLabel Error_F;
    private javax.swing.JLabel Error_LN;
    private javax.swing.JLabel Error_Level;
    private javax.swing.JLabel Error_Rank;
    private javax.swing.JComboBox<String> Faculty;
    private javax.swing.JButton GenerateRankButton;
    private javax.swing.JTextField Lecturer_Name;
    private javax.swing.JTextField Ranks;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAddCS;
    private javax.swing.JLabel labelAddLecturer;
    private javax.swing.JLabel labelAddLocation;
    private javax.swing.JLabel labelAddNAR;
    private javax.swing.JLabel labelAddS;
    private javax.swing.JLabel labelAddSG;
    private javax.swing.JLabel labelAddSession;
    private javax.swing.JLabel labelAddSubject;
    private javax.swing.JLabel labelAddTag;
    private javax.swing.JLabel labelAddWDH;
    private javax.swing.JLabel labelBuilding;
    private javax.swing.JLabel labelCenter;
    private javax.swing.JLabel labelDepartment;
    private javax.swing.JLabel labelEmployeeID;
    private javax.swing.JLabel labelFaculty;
    private javax.swing.JLabel labelLectureLocation;
    private javax.swing.JLabel labelLecturer;
    private javax.swing.JLabel labelLevel;
    private javax.swing.JLabel labelLocations;
    private javax.swing.JLabel labelManageLectureLocation;
    private javax.swing.JLabel labelManageLecturer;
    private javax.swing.JLabel labelManageLocation;
    private javax.swing.JLabel labelManageSG;
    private javax.swing.JLabel labelManageSession;
    private javax.swing.JLabel labelManageSubjects;
    private javax.swing.JLabel labelManageTag;
    private javax.swing.JLabel labelManageWDH;
    private javax.swing.JLabel labelRank;
    private javax.swing.JLabel labelSession;
    private javax.swing.JLabel labelStudentGroup;
    private javax.swing.JLabel labelSubject;
    private javax.swing.JLabel labelTags;
    private javax.swing.JLabel labelTimeAloocation;
    private javax.swing.JLabel labelWorkingDaysHours;
    private javax.swing.JLabel lableDashboard;
    private javax.swing.JLabel lableLectuereName;
    private javax.swing.JComboBox<String> level;
    // End of variables declaration//GEN-END:variables
}
